version: 2
updates:
- package-ecosystem: docker
  directories:
    - "/"
    - "/.devcontainer/"
    - "/docker/"
  cooldown:
    default-days: 7
    exclude:
      - "vscode/devcontainers/typescript-node"
  schedule:
    interval: "cron"
    # Daily at 2 AM
    cronjob: "0 2 * * *"
  open-pull-requests-limit: 10

- package-ecosystem: devcontainers
  directory: "/"
  cooldown:
    default-days: 7
  schedule:
    interval: "cron"
    # Daily at 2 AM
    cronjob: "0 2 * * *"
  open-pull-requests-limit: 10


- package-ecosystem: npm
  directory: "/"
  cooldown:
    default-days: 7
  schedule:
    interval: "cron"
    # Wednesday
    cronjob: "0 2 * * 3"
  open-pull-requests-limit: 20
  target-branch: main
  groups:
    eslint:
      dependency-type: "development"
      patterns:
        - "eslint"
        - "eslint-*"
        - "@eslint/*"
        - "@typescript-eslint/*"
        - "typescript-eslint"
        - "@vue/eslint-*"
    vue:
      patterns:
        - "@vue/*"
        - "vue-*"
        - "vue"
        - "pinia*"
      exclude-patterns:
        - "*eslint*"
        - "vue-echarts"
    vueuse:
      patterns:
        - "@vueuse/*"
    primevue:
      patterns:
        - "primevue*"
        - "@prime*"
    tailwindcss:
      patterns:
        - "tailwind*"
        - "@tailwind*"
    unplugin:
      patterns:
        - "unplugin*"
    date-fns:
      patterns:
        - "date-fns*"


- package-ecosystem: "github-actions"
  directory: "/"
  cooldown:
    default-days: 7
  schedule:
    interval: "cron"
    # Thursday
    cronjob: "0 2 * * 4"
  open-pull-requests-limit: 10
  target-branch: main
  groups:
    docker:
      patterns:
        - "docker/*"
