name: FreqUI CI

on:
  push:
    branches:
      - main
      - ci/**

  pull_request:
    branches:
      - main
  release:
    types: [ published ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Build and Test FreqUI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-24.04 ]
        node: [ "20", "22", "24", "25"]

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false


    - name: Install pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

    - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        node-version: ${{ matrix.node }}
        cache: 'pnpm'


    - run: pnpm install

    - name: Run Lint
      run: pnpm run lint-ci

    - name: Run type check
      run: pnpm run typecheck

    - name: Run Tests
      run: pnpm run test:unit

    - name: Build build
      run: pnpm run build

    - name: Archive artifacts
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      # Ideally this would upload the zip file from below - but this action currently does not support this.
      with:
        name: freqUI-${{ matrix.node }}
        path: |
          dist
          !dist/**/*.map
        retention-days: 10

    # Playwright section
    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps

    - name: Run Playwright tests
      run: pnpm exec playwright test

    - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-${{ matrix.node }}
        path: playwright-report/
        retention-days: 30

    # End Playwright section

  release:
    name: Upload Release Binaries
    runs-on: "ubuntu-latest"
    if: github.event_name == 'release'
    needs: build
    permissions:
      contents: write  # Needed to upload release assets.
    steps:
    - name: Download digests
      uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
      with:
        path: ./dist/
        # Use node-22 build.
        name: freqUI-22

    - name: Zip files for release
      run: |
        cd dist/
        zip -r ../freqUI.zip .
        cd ../

    - name: Upload release binaries
      uses: alexellis/upload-assets@13926a61cdb2cb35f5fdef1c06b8b591523236d3 # 0.4.1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_paths: '["./freqUI.zip"]'

  call-docker-workflow:
    needs: build
    if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'release') && github.repository == 'freqtrade/frequi'
    uses: ./.github/workflows/docker.yml
    permissions:
      packages: write  # Needed to push Docker images to ghcr.
      contents: read
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
