name: FreqUI CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2-beta

    - run: yarn install

    - name: Run Lint
      run: yarn lint-ci

    - name: Run Tests
      run: yarn test:unit

    - name: Build build
      run: yarn build

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      # Ideally this would upload the zipfile from below - but this action currently does not support this.
      with:
        name: freqUI
        path: |
          dist
          !dist/**/*.map
        retention-days: 10

    - name: Zip files for release
      if: github.event_name == 'release'
      run: |
        cd dist/
        zip -r ../freqUI.zip .
        cd ../


    - name: Upload release binaries
      uses: alexellis/upload-assets@0.2.2
      if: github.event_name == 'release'
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_paths: '["./freqUI.zip"]'
